"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Moon,Home,Building2,Coffee,CloudSun,BatteryCharging,TrainFront,Route,Settings2,ChevronRight,Check,RefreshCw,Smartphone,ArrowUpRight} from 'lucide-react';
import WeatherDetail from '@/components/weather-detail';
import CommuteRoute from '@/components/commute-route';
type Base='home'|'london'|'off';
type Plan={date:string;base:Base;range:string;miles:string;reserve:string;rangeDate?:string};
function day(n=0){const d=new Date(new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'})+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function defaults(date:string):Plan{return {date,base:[0,6].includes(new Date(date+'T12:00:00Z').getUTCDay())?'off':'home',range:'',miles:'130',reserve:'30'}}
export default function Page(){
const [date,setDate]=useState(''),[plan,setPlan]=useState<Plan>(defaults('2026-09-12')),[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[settings,setSettings]=useState(false),[saved,setSaved]=useState(false),[loaded,setLoaded]=useState(false),[tesla,setTesla]=useState<any>(null),[weatherFallback,setWeatherFallback]=useState<any>({}),[tubeFallback,setTubeFallback]=useState<any>(null);
useEffect(()=>setDate(day(1)),[]);
useEffect(()=>{if(!date)return;let active=true;setLoaded(false);setSaved(false);setMsg('');fetch('/api/plan?date='+date).then(r=>{if(!r.ok)throw Error();return r.json()}).then((x:any)=>{if(active){setPlan(x.plan||defaults(date));setSaved(!!x.plan);setLoaded(true)}}).catch(()=>{if(active){setPlan(defaults(date));setSaved(false);setLoaded(true);setMsg('Using the default plan. Confirm your day to save it.')}});return()=>{active=false}},[date]);
useEffect(()=>{if(!date)return;let active=true;setBusy(true);setData(null);fetch('/api/briefing?date='+date).then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>active&&setData(x)).catch(()=>active&&setMsg('Briefing unavailable. Refresh to retry.')).finally(()=>active&&setBusy(false));return()=>{active=false}},[date]);
useEffect(()=>{fetch('https://api.tfl.gov.uk/Line/jubilee,circle,hammersmith-city/Status?detail=true').then(r=>r.ok?r.json():null).then(lines=>Array.isArray(lines)&&setTubeFallback({lines})).catch(()=>null)},[]);
useEffect(()=>{if(!date)return;let active=true;const load=(lat:number,lon:number)=>fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,apparent_temperature,precipitation_probability,wind_speed_10m,weather_code&wind_speed_unit=mph&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FLondon&start_date=${date}&end_date=${date}`).then(r=>r.ok?r.json():null).catch(()=>null);Promise.all([load(51.257,1.018),load(51.5154,-0.1755)]).then(([home,work])=>active&&setWeatherFallback({home,work}));return()=>{active=false}},[date]);
useEffect(()=>{fetch('/api/tesla/state',{cache:'no-store'}).then(r=>r.json()).then(setTesla).catch(()=>setTesla({connected:false,error:'Tesla connection check failed'}))},[]);
async function refresh(){setBusy(true);try{const r=await fetch('/api/briefing?date='+date);if(!r.ok)throw Error();setData(await r.json())}catch{setMsg('Refresh failed. Previously shown information may be out of date.')}finally{setBusy(false)}}
async function save(){setMsg('Saving');try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...plan,date})});if(!r.ok)throw Error();setSaved(true);setMsg('Plan saved. Change it whenever you need.')}catch{setMsg('Could not save. Your entries are still here  try again.')}}
const london=plan.base==='london',fresh=plan.rangeDate===day(),charge=london&&fresh&&plan.range!==''&&plan.miles!==''?Number(plan.range)<Number(plan.miles)+Number(plan.reserve):null;
const liveRange=tesla?.vehicle?.rangeMiles!=null?Number(tesla.vehicle.rangeMiles):null, trip=Number(plan.miles)||130, reserve=Number(plan.reserve||0), teslaAnswer=london&&liveRange!=null?(liveRange<trip/2?'plug':liveRange<trip+reserve?'return':'enough'):null;
const tubeData=data?.tube?.lines?.length?data.tube:tubeFallback||data?.tube;
const label=date?new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'}):'Tomorrow';
return <><header><a className="brand" href="/"><span><Moon size={21}/></span>day ahead<b>.</b></a><span className="header-note">A little planning. A lighter morning.</span><Button variant="outline" onClick={()=>setSettings(!settings)}><Settings2/>Your routine</Button></header><main>
<div className="heading"><div><p className="eyebrow">YOUR PERSONAL DAILY BRIEFING</p><h1>Tomorrow, taken care of.</h1><p className="sub">{label}  Europe / London</p></div><label className="date-control">Plan for<Input type="date" value={date} min={day()} max={day(6)} onChange={e=>setDate(e.target.value)}/></label></div>
<div className="layout"><div><section className="checkin"><div className="section-top"><span className="eyebrow">THE EVENING CHECK-IN</span><span className="pill"><Moon size={14}/>20:00</span></div><h2>Where are you based {date===day()?'today':date===day(1)?'tomorrow':'that day'}?</h2><p>Your plans can be flexible. Your morning can still be ready.</p><div className="choices">{([{id:'london',title:'In London',detail:'Your Paddington commute',Icon:Building2},{id:'home',title:'At home',detail:'A day in Chartham',Icon:Home},{id:'off',title:'Day off',detail:'No work, no commute',Icon:Coffee}] as const).map(x=><Button disabled={!loaded} key={x.id} variant="outline" className={'choice '+(plan.base===x.id?'selected':'')} aria-pressed={plan.base===x.id} onClick={()=>{setPlan(p=>({...p,base:x.id}));setSaved(false)}}><x.Icon/><strong>{x.title}</strong><small>{x.detail}</small>{plan.base===x.id&&<Check className="choice-check"/>}</Button>)}</div><div className="checkin-footer"><span>Two flexible London days. Weekends off by default.</span><Button disabled={!loaded} onClick={save}>{saved?'Update plan':'Confirm my day'}<ChevronRight/></Button></div><p className="save-status" role="status">{msg}</p></section>
<div className="brief-title"><h2>Your {date===day()?'morning':'day-ahead'} briefing</h2><Button variant="ghost" disabled={busy} onClick={refresh}><RefreshCw className={busy?'spin':''}/>{busy?'Checking':'Refresh'}</Button></div>
<div className="weather-grid">{(london?['home','work']:['home']).map(place=>{const forecast=data?.weather?.[place]?.hourly?data.weather[place]:weatherFallback[place];return <section className="card weather" key={place}><div className="section-top"><span className="eyebrow">{place==='home'?'AT HOME':'YOUR DESTINATION'}</span><CloudSun size={28}/></div><h3>{place==='home'?'Chartham, Kent':'Paddington, London'}</h3>{forecast?.hourly?<WeatherDetail hourly={forecast.hourly} dateLabel={label}/>:<p>{busy?'Checking forecast':'Weather unavailable. Please refresh.'}</p>}</section>})}</div>
{london?<><section className="card"><div className="card-heading"><span className="icon-box"><Route/></span><div><h3>The drive into London</h3><p>Chartham  North Greenwich station</p></div></div><CommuteRoute roads={data?.roads} date={date} loading={busy}/><p className="notice">Showing incidents and works on your usual A2  M2 route. Other roads appear only when they are a serious reroute risk.</p>{data?.roads?.national_highways?.items?.length?<details open><summary>{data.roads.national_highways.items.length} National Highways closure{data.roads.national_highways.items.length===1?'':'s'} on A2 / M2</summary>{data.roads.national_highways.items.map((r:any,i:number)=><p key={i}><strong>{r.location||r.road||r.roadName||r.category||'A2 / M2'}</strong>  {r.description||r.comments||r.status||'Closure or restriction reported'}</p>)}</details>:<p className="muted">{busy?'Checking National Highways':data?.roads?.national_highways?.message||'No National Highways A2 / M2 closures returned.'}</p>}{data?.roads?.items?.length?<details><summary>{data.roads.items.length} London route report{data.roads.items.length===1?'':'s'}</summary>{data.roads.items.map((r:any,i:number)=><p key={i}><strong>{r.location||r.category}</strong>  {r.comments||r.currentUpdate||'See TfL for details'}</p>)}</details>:null}{data?.roads?.reroutes?.length?<details><summary>{data.roads.reroutes.length} serious disruption{data.roads.reroutes.length===1?'':'s'} elsewhere may require rerouting</summary>{data.roads.reroutes.map((r:any,i:number)=><p key={i}><strong>{r.location||r.category}</strong>  {r.comments||r.currentUpdate||'See TfL for details'}</p>)}</details>:null}<a className="text-link" href="https://www.google.com/maps/dir/Chartham,+Canterbury/North+Greenwich+Station/" target="_blank" rel="noreferrer">Check the full driving route<ArrowUpRight size={16}/></a></section>
<section className="card"><div className="card-heading"><span className="icon-box"><TrainFront/></span><div><h3>Your Underground connection</h3><p>North Greenwich  Baker Street  Paddington</p></div><span className="tag">TfL</span></div><div className="tube-tabs"><i className="tube-dot jubilee"/>Jubilee<ChevronRight size={16}/><i className="tube-dot circle"/>Circle<span className="muted">or</span><i className="tube-dot hammersmith-city"/>Hammersmith & City</div><p className="muted">{date===day()?'Current service status':'Planned status for '+label}. Strikes appear when reported by TfL.</p>{tubeData?.lines?.map((line:any)=><div className="line-status" key={line.id}><div><i className={'tube-dot '+line.id}/><strong>{line.name}</strong></div><span>{line.lineStatuses?.map((s:any)=>s.statusSeverityDescription).join('  ')||'Status unavailable'}</span>{line.lineStatuses?.filter((s:any)=>s.reason).map((s:any,i:number)=><p key={i}>{s.reason}</p>)}</div>)}{tubeData?.error&&<p>{tubeData.error}</p>}<a className="text-link" href="https://tfl.gov.uk/tube-dlr-overground/status/" target="_blank" rel="noreferrer">All lines, planned works and strike updates<ArrowUpRight size={16}/></a></section></>:<section className="card quiet-day"><Coffee size={30}/><div><h3>{plan.base==='off'?'A little room to switch off.':'A shorter journey to your desk.'}</h3><p>{plan.base==='off'?'No work commute planned. Your local forecast is above.':'Your Chartham forecast is above. No London commute planned.'}</p></div></section>}</div>
<aside><section className="routine-card"><p className="eyebrow">A CALMER DAILY RHYTHM</p><h2>Two small check-ins.</h2><div className="timeline"><div><Moon/><p><strong>20:00 <span>The night before</span></strong>Choose where youll be. Check the forecast and charge if needed.</p></div><div><CloudSun/><p><strong>06:00 <span>Before you leave</span></strong>A fresh look at the roads, Tube and weather for your saved plan.</p></div></div><div className="push-state"><Smartphone/><div><strong>iPhone push: setup needed</strong><p>Briefings are available here. Automatic delivery is not active yet.</p></div></div><Button variant="outline" onClick={()=>setSettings(!settings)}>View notification setup<ChevronRight/></Button></section>
<section className="card charging"><div className="section-top"><span className="eyebrow">YOUR TESLA</span><BatteryCharging size={25}/></div>{tesla?.connected&&tesla.vehicle&&tesla.vehicle.chargeLevel!=null?<p className="range-ok">Live charge: {tesla.vehicle.chargeLevel}%  {tesla.vehicle.rangeMiles??""} miles</p>:<Button variant="outline" onClick={()=>location.href="/api/tesla/connect"}>Connect Tesla</Button>}{tesla?.error&&<small className="notice">{tesla.error}</small>}<h3>{!london?'No commute charge check':teslaAnswer==='plug'?'Plug in tonight':teslaAnswer==='return'?'Charge on the way home':teslaAnswer==='enough'?'Enough charge for tomorrow':'Enter your return-trip distance'}</h3><p>Enter todays displayed range and your return driving distance.</p><div className="charge-inputs">{([{key:'range',label:'Range now (miles)',placeholder:'e.g. 160'},{key:'miles',label:'Return trip (miles)',placeholder:'Your round trip'},{key:'reserve',label:'Reserve (miles)',placeholder:'30'}] as const).map(x=><label key={x.key}>{x.label}<Input disabled={!loaded} type="number" min={x.key==='miles'?1:0} max="1000" value={plan[x.key]} placeholder={x.placeholder} onChange={e=>{setPlan(p=>({...p,[x.key]:e.target.value,...(x.key==='range'?{rangeDate:day()}:{})}));setSaved(false)}}/></label>)}</div>{charge!==null&&<p className={charge?'notice':'range-ok'}>{Number(plan.miles)+Number(plan.reserve)} miles needed, including your reserve.</p>}{plan.range&&!fresh&&<p className="notice">Update your range today to check whether to charge.</p>}<small>Manual check. Tesla is not connected; actual range varies with conditions. Confirm your day to save these entries.</small></section></aside></div>
{settings&&<section className="card setup"><h2>Your routine & notifications</h2><div className="setup-grid"><div><h3>Your commute</h3><p>Chartham, Kent  North Greenwich station<br/>Jubilee to Baker Street<br/>Circle or Hammersmith & City to Paddington.</p><p>London twice a week on days you choose. Weekends default to a day off.</p></div><div><h3>iPhone push is not active</h3><p>The requested times are 20:00 and 06:00 in Europe/London, including daylight saving changes. A background scheduler and push service still need connecting.</p><p>For iPhone web push, the app must also be added to the Home Screen and notification permission granted. No notification permission is requested until delivery is connected.</p></div></div></section>}
<footer><span>Made for your day, wherever it takes you.</span><span>Weather: <a href="https://open-meteo.com/">Open-Meteo</a>  Travel: <a href="https://tfl.gov.uk/">TfL</a>{data?.checkedAt?'  Checked '+new Date(data.checkedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'}):''}</span></footer></main></>}


