import {env} from 'cloudflare:workers';
async function json(url:string,headers:Record<string,string>={}){const r=await fetch(url,{signal:AbortSignal.timeout(12000),headers:{Accept:'application/json',...headers}});if(!r.ok)throw Error('Provider unavailable');return r.json();}
async function nationalHighways(date:string){const key=(env as unknown as Record<string,unknown>).NATIONAL_HIGHWAYS_SUBSCRIPTION_KEY; if(typeof key!=='string'||!key)return {configured:false,items:[],message:'National Highways access key not configured'};try{const q=new URLSearchParams({startDateTime:`${date}T00:00:00Z`,endDateTime:`${date}T23:59:59Z`});const raw:any=await json(`https://api.data.nationalhighways.co.uk/roads/v2.0/closures?${q}`,{'Ocp-Apim-Subscription-Key':key});const list=Array.isArray(raw)?raw:(raw.closures||raw.results||raw.data||[]);const text=(r:any)=>JSON.stringify(r).toLowerCase();const route=list.filter((r:any)=>/(^|[^a-z0-9])a\s*2([^a-z0-9]|$)|(^|[^a-z0-9])m\s*2([^a-z0-9]|$)|dartford|north greenwich|medway|rochester|canterbury/.test(text(r)));return {configured:true,items:route.slice(0,30)};}catch{return {configured:true,items:[],message:'National Highways feed unavailable'}}}
async function weather(lat:number,lon:number,date:string){try{return await json(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,apparent_temperature,precipitation_probability,wind_speed_10m,weather_code&wind_speed_unit=mph&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FLondon&start_date=${date}&end_date=${date}`)}catch{return {error:'Weather provider unavailable. Try Refresh.'}}}
export async function GET(req:Request){const date=new URL(req.url).searchParams.get('date')||'';if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||isNaN(Date.parse(date)))return Response.json({error:'Invalid date'},{status:400});const today=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'});const tubeUrl=date===today?'https://api.tfl.gov.uk/Line/jubilee,circle,hammersmith-city/Status?detail=true':`https://api.tfl.gov.uk/Line/jubilee,circle,hammersmith-city/Status/${date}T00:00:00/to/${date}T23:59:59?detail=true`;
const [home,work,tube,roads,national]=await Promise.all([weather(51.257,1.018,date),weather(51.5154,-0.1755,date),json(tubeUrl).then(lines=>Array.isArray(lines)?{lines}:{error:'Tube status unavailable'}).catch(()=>({error:'TfL status unavailable. Check the TfL link for updates.'})),json('https://api.tfl.gov.uk/Road/all/Disruption').then(items=>{if(!Array.isArray(items))return {error:'London route reports unavailable'};const active=items.filter((r:any)=>(!r.startDateTime||r.startDateTime.slice(0,10)<=date)&&(!r.endDateTime||r.endDateTime.slice(0,10)>=date));const routeText=(r:any)=>JSON.stringify(r).toLowerCase();const routeItems=active.filter((r:any)=>(/(^|[^a-z0-9])a\\s*2([^a-z0-9]|$)|(^|[^a-z0-9])m\\s*2([^a-z0-9]|$)|north greenwich|dartford crossing|blackwall/).test(routeText(r)));const reroutes=active.filter((r:any)=>!routeItems.includes(r)&&/(severe|serious|major|closure|closed|diversion|blocked|incident|collision)/i.test(`${r.severity} ${r.category} ${r.comments} ${r.currentUpdate}`));const shape=(r:any)=>({location:r.location,category:r.category,comments:r.comments,currentUpdate:r.currentUpdate,severity:r.severity});return {route:'A2 → M2 → North Greenwich',items:routeItems.map(shape),reroutes:reroutes.slice(0,10).map(shape)};}).catch(()=>({error:'London route reports unavailable.'})),nationalHighways(date)]);return Response.json({weather:{home,work},tube,roads:{...roads,national_highways:national},checkedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}})}



